name: "Archive Artifacts Composite Action"
description: "Archives a list of web artifacts (with optional descriptions), generates files, commits changes, and deploys to GitHub Pages."

inputs:
  artifacts:
    description: >
      A JSON array of artifact objects. Each object must include a "url" property and can optionally include a "description".
      Example:
      [
        { "url": "https://example.com", "description": "Example website" },
        { "url": "r/AskReddit", "description": "Subreddit Wiki for AskReddit" },
        { "url": "https://example.com/file.pdf" }
      ]
    required: true
  schedule:
    description: 'A description of the schedule (e.g., "Daily at midnight (UTC)")'
    required: false
    default: 'Daily at midnight (UTC)'
  contact_email:
    description: "Optional contact email to include in the README"
    required: false
  limit_rate:
    description: "Optional download speed limit for wget (e.g., '10m' for 10MB/s)."
    required: false
  user_agent:
    description: "Optional user-agent string for wget requests. Defaults to a spoofed Chrome user-agent."
    required: false
  github_token:
    description: "GitHub token for committing changes and deploying to GitHub Pages."
    required: true

runs:
  using: "node16"
  main: "dist/index.js"